server:
  port: 9090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      server:
        webflux:
          routes:
            - id: greet-service
              uri: lb://GREETAPI-PROJECT-MICROSERVICES
              predicates:
                - Path=/greet/**

            - id: welcome-service
              uri: lb://WELCOMEAPI-PROJECT-MICROSERVICES
              predicates:
                - Path=/wel/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
